### ISSUE TITLE
error compile this package with moveit master branch

### ISSUE THREAD

**Issue by lianghongzhuo** [TAMS-Group/bio_ik#25]
In the [geometric_shapes](https://github.com/ros-planning/geometric_shapes) write:
> Note: `bodies::ConvexMesh::MeshData` was made implementation-private in Noetic and is no longer accessible from the `.h` file.

That leads to the compile error in bio_ik moveit master branch
error msg is: 
```
/bio_ik/src/goal_types.cpp:89:49: error: invalid use of incomplete type ‘using element_type = struct bodies::ConvexMesh::MeshData {aka struct bodies::ConvexMesh::MeshData}’
                         for(auto& v : mesh_data_->vertices_)

```

**Comment by v4hn** [comment]
This error turns up if you do not compile a current release of libfcl (0.6.x) as well. You can add that to your MoveIt workspace [as described here](https://moveit.ros.org/install/source/dependencies/).

That being said the error is actually unrelated and it could probably be fixed by adapting bio_ik to the new geometric_shapes API.

We should probably either fix the FCL 0.6 build issues AND the new issue you describe here, or just drop the `TouchGoal` from the library altogether...

**Comment by lianghongzhuo** [comment]
Using fcl master branch is not helpful. I still got the same error.

**Comment by v4hn** [comment]
> Using fcl master branch is not helpful. I still got the same error.

Then you did not integrate fcl correctly and catkin still prefers the system version over the one in your workspace.

As I told you in person before, the sure-fire alternative is to simply remove the offending `#ifdef` blocks from the sources.

**Comment by lianghongzhuo** [comment]
Got it. But keep this issue open for tracking this issue.
